# extra, remove
version: '3'
services:
  client:
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '3030:3030'
    build:
      dockerfile: Dockerfile
      context: ./client
